id = "eliots-theme"
name = "Eliot's Theme"
version = "1.0.0"
schema_version = 1
authors = ["Eliot Chignell <chignelleliot@gmail.com>"]
description = "A dark purple-ish blurred theme based off nightfox.zed."
repository = "https://github.com/EliotChignell/eliots-theme"

[themes]
themes = ["themes/eliots-theme.json"]
